
import 'package:farmayopin/pages/home.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const FarmayoppinApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FarmayoppinApp extends StatelessWidget {
  const FarmayoppinApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomePage()
    );
  }
}

